apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "{{ .Values.name }}-sub"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: {{ .Values.operatorName }}
  source: operatorhubio-catalog
  sourceNamespace: olm