apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awx-demo-ingress
  namespace: awx
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  rules:
    - host: awx.apps.hyperpixel.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: awx-demo-service
                port:
                  number: 80