apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: linkwarden
 name: linkwarden
spec:
 replicas: 3
 selector:
   matchLabels:
     app: linkwarden
 template:
   metadata:
     labels:
       app: linkwarden
   spec:
     containers:
      - name: linkwarden
        imagePullPolicy: IfNotPresent
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: linkwarden-pg-pguser-linkwarden-pg-admin
                key: uri
          - name: NEXTAUTH_SECRET
            value: supersecret-value-two
          - name: NEXTAUTH_URL
            value: https://links.hyperpixel.net/api/v1/auth
          - name: SPACES_KEY
            valueFrom:
              secretKeyRef:
                name: linkwarden-s3
                key: AWS_ACCESS_KEY_ID
          - name: SPACES_SECRET
            valueFrom:
              secretKeyRef:
                name: linkwarden-s3
                key: AWS_SECRET_ACCESS_KEY
          - name: SPACES_ENDPOINT
            value: http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc:80
          - name: SPACES_BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                name: linkwarden-s3
                key: BUCKET_NAME
          - name: SPACES_REGION
            value: us-east-1
          - name: SPACES_FORCE_PATH_STYLE
            value: "true"
        image: ghcr.io/linkwarden/linkwarden:latest
        ports:
          - containerPort: 3000
        resources:
          limits:
            memory: 5Gi
          requests:
            memory: 5Gi
            cpu: 10m