plugin: community.general.proxmox
url: "{{ lookup('env', 'PROXMOX_URL') }}"
user: "{{ lookup('env', 'PROXMOX_USER') }}"
token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
validate_certs: false
want_facts: true
qemu_extended_statuses: true
want_proxmox_nodes_ansible_host: true
hostname: inventory_hostname